ci: wip ... 2

diff --git a/.github/workflows/CI-publish.yaml b/.github/workflows/CI-publish.yaml
--- a/.github/workflows/CI-publish.yaml
+++ b/.github/workflows/CI-publish.yaml
@@ -10,32 +10,18 @@ on:
     types:
       - completed
 jobs:
-  check-tag:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check if the event is a tag push
-        id: check
-        run: |
-          echo "Triggered by ref: ${{ github.ref }}"
-          if [[ "${GITHUB_REF}" =~ tags ]]; then
-            echo "This is a tag push."
-            echo "is_tag=true" >> $GITHUB_ENV
-            echo "::set-output name=is_tag::true"
-          else
-            echo "This is NOT a tag push."
-            echo "is_tag=false" >> $GITHUB_ENV
-            echo "::set-output name=is_tag::false"
-          fi
   check-status:
+    name: Check Test and Lint Status
     runs-on: ubuntu-latest
-    needs: check-tag
-    if: needs.check-tag.outputs.is_tag == 'true'
     steps:
-      - name: Get lint and test status
-        run: |
-          # [NOTE] This is just for debugging. You hopefully never get this far if lint or test fails.
-          echo "Lint: ${{ github.event.workflow_run.outputs.lint_status }}"
-          echo "Test: ${{ github.event.workflow_run.outputs.test_status }}"
+      name: Get Ref and Tag Info
+      run: |
+        echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
+        echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
+        if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
+          echo "This is not a tag push. Aborting."
+          exit 1
+        fi
   build:
     runs-on: ubuntu-latest
     needs: check-status
