ci: wip ... 3

diff --git a/.github/workflows/CI-publish.yaml b/.github/workflows/CI-publish.yaml
--- a/.github/workflows/CI-publish.yaml
+++ b/.github/workflows/CI-publish.yaml
@@ -14,14 +14,14 @@ jobs:
     name: Check Test and Lint Status
     runs-on: ubuntu-latest
     steps:
-      name: Get Ref and Tag Info
-      run: |
-        echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
-        echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
-        if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
-          echo "This is not a tag push. Aborting."
-          exit 1
-        fi
+      - name: Get Ref and Tag Info
+        run: |
+          echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
+          echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
+          if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
+            echo "This is not a tag push. Aborting."
+            exit 1
+          fi
   build:
     runs-on: ubuntu-latest
     needs: check-status
